import type { Metadata } from "next";
import "./globals.css";
import Drawer from "../components/Drawer";
// import Sidebar from "./components/Sidebar";
import "./globals.css";

import { Roboto } from "next/font/google";
import { ThemeProvider } from "./utils/ThemeProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // Optional: specify weights
  variable: "--font-roboto", // Optional CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <ThemeProvider>
        <body className={`flex ${roboto.variable}`}>
          <Drawer />
          <main className="flex-1 p-3 bg-gray-50 min-h-screen">{children}</main>
        </body>
      </ThemeProvider>
    </html>
  );
}
